// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/AutoInput/index":{"id":"components/AutoInput/index","path":"components/auto-input","parentId":"DocLayout"},"components/Button/index":{"id":"components/Button/index","path":"components/button","parentId":"DocLayout"},"components/Carousel/index":{"id":"components/Carousel/index","path":"components/carousel","parentId":"DocLayout"},"components/Icon/index":{"id":"components/Icon/index","path":"components/icon","parentId":"DocLayout"},"components/Input/index":{"id":"components/Input/index","path":"components/input","parentId":"DocLayout"},"components/Install/index":{"id":"components/Install/index","path":"components/install","parentId":"DocLayout"},"components/Introduce/index":{"id":"components/Introduce/index","path":"components/introduce","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "D:__前端学习__warehouse-ikun__warehouse-ikun__node_modules__dumi__dist__client__pages__404" */'D:/前端学习/warehouse-ikun/warehouse-ikun/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/.dumi/tmp-production/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "D:__前端学习__warehouse-ikun__warehouse-ikun__node_modules__dumi__theme-default__layouts__DocLayout__index" */'D:/前端学习/warehouse-ikun/warehouse-ikun/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/docs/index.md')),
'components/AutoInput/index': React.lazy(() => import(/* webpackChunkName: "AutoInput__index.md" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/src/AutoInput/index.md')),
'components/Button/index': React.lazy(() => import(/* webpackChunkName: "Button__index.md" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/src/Button/index.md')),
'components/Carousel/index': React.lazy(() => import(/* webpackChunkName: "Carousel__index.md" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/src/Carousel/index.md')),
'components/Icon/index': React.lazy(() => import(/* webpackChunkName: "Icon__index.md" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/src/Icon/index.md')),
'components/Input/index': React.lazy(() => import(/* webpackChunkName: "Input__index.md" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/src/Input/index.md')),
'components/Install/index': React.lazy(() => import(/* webpackChunkName: "Install__index.md" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/src/Install/index.md')),
'components/Introduce/index': React.lazy(() => import(/* webpackChunkName: "Introduce__index.md" */'D:/前端学习/warehouse-ikun/warehouse-ikun/dumi/src/Introduce/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "D:__前端学习__warehouse-ikun__warehouse-ikun__node_modules__dumi__dist__client__pages__Demo__index" */'D:/前端学习/warehouse-ikun/warehouse-ikun/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
