// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/前端学习/warehouse-ikun/warehouse-ikun/node_modules/dumi/theme-default/slots/ContentTabs/index.js';
