// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from 'D:/前端学习/warehouse-ikun/warehouse-ikun/node_modules/dumi/dist/client/theme-api/index.js';
